on: [push]  

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      
      - name : message check
        run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
        if: ${{ !contains(${MSG}, 'feat') || !contains(${MSG}, 'fix') }}
        run: exit 1      

  semantic-version-update-call:
    needs: [commit-message-check]
    uses: ./.github/workflows/semantic_version_release.yml
    
  dotnetcore-call:
    needs: [semantic-version-update-call]
    uses: ./.github/workflows/dotnetcore.yml
