name: Semantic Version Release

on: [push]  

jobs:
  Semantic-Version-Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.NK_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          semantic_version: 19

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with: 
          dir_names: "true"

      - name: List all changed files        
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if: steps.changed-files.outputs.all_changed_files == 'Philips.CodeAnalysis.MoqAnalyzers'
            run: |
              sed -i -e "s+<version>.*</version>+<version>${{ steps.semantic.outputs.new_release_version }}</version>+g" steps.changed-files.outputs.all_changed_files/steps.changed-files.outputs.all_changed_files.csproj
          done