name: Semantic Version Release

on: [push]  

jobs:
  Semantic-Version-Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.NK_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          semantic_version: 19

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            Philips.CodeAnalysis.MoqAnalyzers/**

      - name: Run step if any file(s) in the MoqAnalyzers project change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          sed -i -e "s+<version>.*</version>+<version>${{ steps.semantic.outputs.new_release_version }}</version>+g" ${{ steps.changed-files.outputs.all_changed_files }}/${{ steps.changed-files.outputs.all_changed_files.csproj }}

      